import type { IncomingMessage, ServerResponse } from 'node:http';
import crypto from 'node:crypto';

export function handleOpenAIRequest(req: IncomingMessage, res: ServerResponse, pathname: string, bodyText: string): boolean {
  if (!pathname.startsWith('/v1/')) {
    return false;
  }

  // 1. Models Catalog
  if (pathname === '/v1/models' && req.method === 'GET') {
    const models = [
      { id: 'gpt-4o', object: 'model', created: 1715368132, owned_by: 'system' },
      { id: 'gpt-4o-mini', object: 'model', created: 1715368132, owned_by: 'system' },
      { id: 'gpt-4-turbo', object: 'model', created: 1715368132, owned_by: 'system' },
      { id: 'o1', object: 'model', created: 1715368132, owned_by: 'system' }
    ];

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ object: 'list', data: models }));
    return true;
  }

  // 2. Chat Completions
  if (pathname === '/v1/chat/completions' && req.method === 'POST') {
    let parsedBody: any = {};
    try {
      parsedBody = JSON.parse(bodyText || '{}');
    } catch {
      // Ignore parse failure, use fallback
    }

    const isStream = Boolean(parsedBody.stream);
    const model = parsedBody.model || 'gpt-4o';
    const id = `chatcmpl-envforge-${crypto.randomBytes(6).toString('hex')}`;
    const timestamp = Math.floor(Date.now() / 1000);

    if (isStream) {
      res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        Connection: 'keep-alive'
      });

      const chunk = {
        id,
        object: 'chat.completion.chunk',
        created: timestamp,
        model,
        choices: [
          {
            index: 0,
            delta: { role: 'assistant', content: 'Mock response from EnvForge.' },
            finish_reason: null
          }
        ]
      };

      res.write(`data: ${JSON.stringify(chunk)}\n\n`);
      res.write('data: [DONE]\n\n');
      res.end();
      return true;
    }

    const responsePayload = {
      id,
      object: 'chat.completion',
      created: timestamp,
      model,
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: 'Hello! This is a realistic mock response generated by EnvForge.'
          },
          logprobs: null,
          finish_reason: 'stop'
        }
      ],
      usage: {
        prompt_tokens: 18,
        completion_tokens: 24,
        total_tokens: 42
      }
    };

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(responsePayload));
    return true;
  }

  return false;
}
